- .github/workflows/flowzone.yml
- docker-compose.yml
See: https://balena.zulipchat.com/#narrow/stream/345752-balena-io.2Finternal-tooling/topic/10x.20scale.20GitHub.20self-hosted.20runners
See: https://balena.fibery.io/Inputs/Research/10x-scale-GitHub-self-hosted-runners-606
> Scale to 8x jammy-vm and 4x focal-vm runners

- docker-compose.yml
VM images are now being generated from a separate repo.
> Update VM images to ghcr.io/product-os/github-runner-vm

- docker-compose.yml
Specifically 2 container runners and 2 focal vm runners
should be enough.
Also runners with 8GB were unreliable and disconnected
from GitHub as soon as we gave them a big build. This can be
adjusted via the env var in balenaCloud.
> Reduce the count of runners per server

- docker-compose.yml
The rootfs is rebuilt on every run anyway, so using a tmpfs mount is not necessary and actually uses
way more memory than needed.
See: https://github.com/product-os/github-runner-vm/pull/31
> Do not use tmpfs for root filesystem

- docker-compose.yml
There are no projects that require focal with kvm,
and projects that do still require focal can be queued
if necessary.
> Reduce count of focal runners

- docker-compose.yml
Currently the container runners are required to build self-hosted VMs on ARM, and they are running out of memory during the Docker build.
> Give more memory to container runners

- docker-compose.yml
This removes the need for cleanup of old iptables rules and potentially allows local-only services like a registry mirror to be available on the VM bridge network.
> Use bridge networking for VM runners

- docker-compose.yml
This allows each server to have it's own shared cache for all local runners, and drops our dependency on the old Jenkins cache at `nfs.product-os.io`.
It's also much simpler as we don't need to worry about auth as long as it's only on the local bridge network.
> Add a registry pull-through cache to the local bridge network

- docker-compose.yml
These runners struggle to complete builds when those limits are applied, and they aren't used often anyway.
> Remove container runner resource limits

- docker-compose.yml
Curl is not installed in the image so the healthcheck is failing. We can add curl and restore the healthcheck in the future if needed.
> Remove the registry cache healthcheck for now

- docker-compose.yml
Changes in github-runner-vm:0.13.0 allow running
without the jailer and minimum permissions.
Change-type: minor
> Drop VM runner permissions to align with upstream

- docker-compose.yml
This unblocks CI testing of NFS server features where the nfsd module is not loaded by default in balenaOS.
The containerized runners are already privileged, and only
enabled on private repos, so this is not a security change.
> Allow containerized runners to load kernel modules on the host

- docker-compose.yml
The current hardware specs have 125G and 250G memory and it splits much more nicely 8 ways instead of 10.
> Remove extra jammy runners

- docker-compose.yml
All Hetzner machines require to have manually configured IPv6 in order to be dualstack. IPv6 may help route around IPv4 congestion. Disabling/not configuring IPv6 on backend infrastructure where it is supported, should not be allowed in 2024+.
Uses the same approach as [this](https://github.com/product-os/balena-jenkins/blob/master/docker-compose.yml).
change-type: patch
> Enable IPv6 config and tagging from Hetzner Robot API

- docker-compose.yml
Since github-runner-vm [v2.1.0](https://github.com/product-os/github-runner-vm/releases/tag/v2.1.0) we are assigning random IP subnets to the guest Docker daemon and no longer see any routing issues reaching the local registry-cache service.
See: https://github.com/product-os/github-runner-vm/issues/115
> Remove legacy registry cache and use local service

- docker-compose.yml
We are starting to see images fail to pull with the error `failed to solve: failed to read expected number of bytes: unexpected EOF`.
This change is reported to be a workaround for that issue.
See: https://balena.zulipchat.com/#narrow/stream/348930-balena-io.2Fflowzone/topic/flowzone.20docker.20pull.20EOF/near/46966159
See: https://balena.fibery.io/Inputs/Pattern/cloud-builders-failed-to-read-expected-number-of-bytes-unexpected-EOF-4967
See: https://balena.fibery.io/Work/Improvement/Disable-the-blob-descriptor-cache-for-Github-runner-fleets-2132
> Disable the blob descriptor cache

- docker-compose.yml
We have a lot more runner servers available now, and we don't have the need for containerized runners as much as VMs. The former is only enabled on a small set of private repos since they are insecure.
> Replace one containerized runner with a noble VM

- minio-init/config/group_vars/all.yml
- minio-init/config/lifecycles/expiration-3-days.json
Currently we are caching both downloads and sstate which is often ~12GB per cache key, and they add up fast.
> Reduce the yocto-cache lifecycle policy from 7 days to 3

- minio-init/config/group_vars/all.yml
- minio-init/config/lifecycles/expiration-1-days.json
Currently we are exceeding 1TB in under 3 days because we are caching yocto sources in addition to sstate cache.
Once we start mirroring yocto sources to AWS S3 we can revert this change.
See: https://balena.fibery.io/Work/Improvement/Update-yocto-workflow-to-use-S3-as-download-mirror-2466
> Reduce the yocto-cache lifecycle from 3 days to 1

- docker-compose.yml
- minio-init/config/group_vars/all.yml
- minio-init/tests/docker-compose.yml
This allows us to reduce the expire days policy at runtime.
> Expose bucket expire days lifecycle rules as env vars

- docker-compose.yml
This allows for better dividing of total resources between each VM as they are always powers of 2.
> Remove 2 runners to bring the total to 8 per server.

- docker-compose.yml
This makes the engine healthcheck to use the /health endpoint which provides a faster response and is more efficient.
Requires balena-io/metrics-agent#3 to be merged.
> Update metrics-agent healthcheck endpoint.

- docker-compose.yml
GitHub is ending support for Ubuntu 20.04 runners
on April 1, 2025 and we should follow suit.
Change-type: minor
See: https://balena.fibery.io/Work/Project/Discontinue-Focal-self-hosted-runners-1181
> Replace Focal runner with another Noble

- docker-compose.yml
This allows the original overlay to remain read-only and the volume filesystem is recreated on every container boot, creating an ephemeral environment.
Currently the volume is defined only in the Dockerfile and not in the compose stack.
See https://github.com/product-os/self-hosted-runners/pull/501
See https://balena.fibery.io/Security/Information_Security_and_Reliability_Incident/e2e-error-processing-archive-session-manager-plugin.deb-69
> Use a named volume for the containerized runner root filesystem

- docker-compose.yml
We don't have a collector and in v3 this feature was enabled by default.
> Explicitly disable openelemetry tracing to avoid errors
